// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function GetBackendURL() {
  return window['go']['main']['App']['GetBackendURL']();
}

export function GetDotaPath() {
  return window['go']['main']['App']['GetDotaPath']();
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetMode() {
  return window['go']['main']['App']['GetMode']();
}

export function InstallGSI() {
  return window['go']['main']['App']['InstallGSI']();
}

export function IsDotaInstalled() {
  return window['go']['main']['App']['IsDotaInstalled']();
}

export function IsGSIInstalled() {
  return window['go']['main']['App']['IsGSIInstalled']();
}

export function IsServerRunning() {
  return window['go']['main']['App']['IsServerRunning']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function ProxyToBackend(arg1, arg2, arg3) {
  return window['go']['main']['App']['ProxyToBackend'](arg1, arg2, arg3);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetMode(arg1) {
  return window['go']['main']['App']['SetMode'](arg1);
}

export function StartEmbeddedServer() {
  return window['go']['main']['App']['StartEmbeddedServer']();
}

export function StopEmbeddedServer() {
  return window['go']['main']['App']['StopEmbeddedServer']();
}
