// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWindow():Promise<void>;

export function GetBackendURL():Promise<string>;

export function GetDotaPath():Promise<string>;

export function GetLanguage():Promise<string>;

export function GetMode():Promise<string>;

export function InstallGSI():Promise<Record<string, any>>;

export function IsDotaInstalled():Promise<Record<string, any>>;

export function IsGSIInstalled():Promise<boolean>;

export function IsServerRunning():Promise<boolean>;

export function MinimizeWindow():Promise<void>;

export function ProxyToBackend(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetMode(arg1:string,arg2:string):Promise<void>;

export function StartEmbeddedServer():Promise<void>;

export function StopEmbeddedServer():Promise<void>;
